module.exports = {
	gladysScriptUn: 'SCRIPT1',
	gladysScriptDeux: 'SCRIPT2',
	gladysScriptTrois: 'SCRIPT3',
	gladysScriptQuatre: 'SCRIPT4',
	gladysScriptCinq: 'SCRIPT5',
	gladysScriptSix: 'SCRIPT6',
	gladysScriptSept: 'SCRIPT7',
	gladysScriptHuit: 'SCRIPT8',
	gladysScriptNeuf: 'SCRIPT9',
	gladysScriptDix: 'SCRIPT10',
	gladysScriptUnValue: '1',
	gladysScriptDeuxValue: '2',
	gladysScriptTroisValue: '3',
	gladysScriptQuatreValue: '4',
	gladysScriptCinqValue: '5',
	gladysScriptSixValue: '6',
	gladysScriptSeptValue: '7',
	gladysScriptHuitValue: '8',
	gladysScriptNeufValue: '9',
	gladysScriptDixValue: '10',
	
};